# Generated by Django 3.2.8 on 2021-10-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211004_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='image'),
        ),
    ]
