# Generated by Django 3.2.8 on 2021-10-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20211022_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
