# Generated by Django 3.2.8 on 2021-10-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_comments_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-time']},
        ),
    ]
