# Generated by Django 3.2.8 on 2021-11-02 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='posts.post'),
        ),
    ]
