# Generated by Django 3.2.5 on 2021-10-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_education_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='aziz1', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
