# Generated by Django 3.2.5 on 2021-10-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='asd', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
