# Generated by Django 3.2.8 on 2021-10-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
