# Generated by Django 3.2.8 on 2021-10-22 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_account_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
