# Generated by Django 3.2.8 on 2021-10-23 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_account_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='postlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
