# Generated by Django 3.2.8 on 2021-10-23 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_comments_options'),
        ('accounts', '0015_auto_20211023_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='postlikes', to='posts.Post'),
        ),
    ]
