# Generated by Django 3.2.8 on 2021-10-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20211023_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='single',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=50, null=True),
        ),
    ]
